apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: PreSync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ghcr.io/mongamae-nioh/test-app:latest
        env:
        - name: POSTGRES_HOST
          value: "database"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "example"
        - name: POSTGRES_USER
          value: "example"
        - name: POSTGRES_PASSWORD
          value: "example"
