apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "example"
        - name: POSTGRES_PASSWORD
          value: "example"
        - name: POSTGRES_DB
          value: "example"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
