name: create-pr
on:
  push:
    branches:
      - 'feature/image-updater-**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'chore: image update',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'main',
              body: 'This is an automated PR for image update.'
            });